"use strict";
let itemStyle = "";

const items = {
    // Blocks
    stone: ["block", 64],
    ironBlock: ["block", 32],
    goldBlock: ["block", 32],
    amethystBlock: ["block", 32],
    diamondBlock: ["block", 32],
    sapphireBlock: ["block", 32],
    emeraldBlock: ["block", 32],
    rubyBlock: ["block", 32],
    spinelBlock: ["block", 32],
    // Items
    stick: ["item", 64],
    // Armor/Tools
    woodHelmet: ["helmet", 1],
    woodChestplate: ["chestplate", 1],
    woodLeggings: ["leggings", 1],
    woodBoots: ["boots", 1],
    woodSword: ["weapon", 1],
    woodPickaxe: ["weapon", 1],
    woodAxe: ["weapon", 1],
    woodShovel: ["weapon", 1],
    woodHoe: ["weapon", 1],
    ironHelmet: ["helmet", 1],
    ironChestplate: ["chestplate", 1],
    ironLeggings: ["leggings", 1],
    ironBoots: ["boots", 1],
    ironSword: ["weapon", 1],
    ironPickaxe: ["weapon", 1],
    ironAxe: ["weapon", 1],
    ironShovel: ["weapon", 1],
    ironHoe: ["weapon", 1],
    goldHelmet: ["helmet", 1],
    goldChestplate: ["chestplate", 1],
    goldLeggings: ["leggings", 1],
    goldBoots: ["boots", 1],
    goldSword: ["weapon", 1],
    goldPickaxe: ["weapon", 1],
    goldAxe: ["weapon", 1],
    goldShovel: ["weapon", 1],
    goldHoe: ["weapon", 1],
    amethystHelmet: ["helmet", 1],
    amethystChestplate: ["chestplate", 1],
    amethystLeggings: ["leggings", 1],
    amethystBoots: ["boots", 1],
    amethystSword: ["weapon", 1],
    amethystPickaxe: ["weapon", 1],
    amethystAxe: ["weapon", 1],
    amethystShovel: ["weapon", 1],
    amethystHoe: ["weapon", 1],
    diamondHelmet: ["helmet", 1],
    diamondChestplate: ["chestplate", 1],
    diamondLeggings: ["leggings", 1],
    diamondBoots: ["boots", 1],
    diamondSword: ["weapon", 1],
    diamondPickaxe: ["weapon", 1],
    diamondAxe: ["weapon", 1],
    diamondShovel: ["weapon", 1],
    diamondHoe: ["weapon", 1],
    sapphireHelmet: ["helmet", 1],
    sapphireChestplate: ["chestplate", 1],
    sapphireLeggings: ["leggings", 1],
    sapphireBoots: ["boots", 1],
    sapphireSword: ["weapon", 1],
    sapphirePickaxe: ["weapon", 1],
    sapphireAxe: ["weapon", 1],
    sapphireShovel: ["weapon", 1],
    sapphireHoe: ["weapon", 1],
    emeraldHelmet: ["helmet", 1],
    emeraldChestplate: ["chestplate", 1],
    emeraldLeggings: ["leggings", 1],
    emeraldBoots: ["boots", 1],
    emeraldSword: ["weapon", 1],
    emeraldPickaxe: ["weapon", 1],
    emeraldAxe: ["weapon", 1],
    emeraldShovel: ["weapon", 1],
    emeraldHoe: ["weapon", 1],
    rubyHelmet: ["helmet", 1],
    rubyChestplate: ["chestplate", 1],
    rubyLeggings: ["leggings", 1],
    rubyBoots: ["boots", 1],
    rubySword: ["weapon", 1],
    rubyPickaxe: ["weapon", 1],
    rubyAxe: ["weapon", 1],
    rubyShovel: ["weapon", 1],
    rubyHoe: ["weapon", 1],
    spinelHelmet: ["helmet", 1],
    spinelChestplate: ["chestplate", 1],
    spinelLeggings: ["leggings", 1],
    spinelBoots: ["boots", 1],
    spinelSword: ["weapon", 1],
    spinelPickaxe: ["weapon", 1],
    spinelAxe: ["weapon", 1],
    spinelShovel: ["weapon", 1],
    spinelHoe: ["weapon", 1],
};

Object.getOwnPropertyNames(items).forEach(name => {
    itemStyle += `[data-item='${name}']{background-image:url(img/items/${name}.png)}`;
});

document.querySelector("style").innerHTML = itemStyle;
